spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testTodo;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: root
    password: guddn123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true